### ISSUE TITLE
Contract propagation

### ISSUE THREAD

**Issue by pdaw** [lisachenko/php-deal#9]
I wonder if we could inherit contacts from parent classes.

For example, we define an interface with common contract and all children (without own contract) would be obligated to fulfills parent's requirements.

I'm not sure if it's possible with goaop/framework.

**Comment by lisachenko** [comment]
Sorry, I'm going to sleep now, can discuss tomorrow.

In short: this is doable in runtime, we just take our method, then recursively ask for prototype method or for parent class, then take our annotations and just run them all.

**Comment by pdaw** [comment]
Cya. To read tommorow - all right, but do we have to do it manually with pure reflection mechanism or goaop/framework can create some Stub with inherited annotations?

**Comment by lisachenko** [comment]
@pdaw I think `goaop` can't help here, it just puts an interceptor in the source code, but logic of interceptors described in the concrete aspects, for example, in `ContractCheckerAspect`, etc.

PhpDeal otherwise, can handle this specific job pretty nice by looking at parent methods and querying annotations from them, so all contracts from the parent classes will be applied too. As DbC is development-only tool (it's recommended as a best practice, no contract checks in production mode), this reflection API shouldn't be a performance killer (can be pre-cached in array like this Class::method => array of contracts)

**Comment by pdaw** [comment]
I get it, may you tag it as enhancement?

**Comment by pdaw** [comment]
@lisachenko 

I think it can works in two modes:
1. Contract overrides parents' contracts if it's defined. Otherwise parents' contracts are applied.
2. Contract does not override parents' contracts, so all contracts are executed.

It would be handled with some extra annotation, ex. @Contract\Override. Default version may be the second one.

**Comment by lisachenko** [comment]
H! There are rules for applying DbC contracts for inheritance (these rules are based on Liskov principle): 

 1. Subclasses in an inheritance hierarchy **are allowed to weaken preconditions** (but not strengthen them)
 2. Subclasses in an inheritance hierarchy **are allowed to strengthen postconditions and invariants** (but not weaken them).

So, for all **Ensure** and **Invariant** annotations we MUST collect all parents annotations and check them. If we have some more postconditions in the current class, they should be verified as well. But we SHOULD check if the parent method defines exactly the same contract to execute it only once.

For **Verify** annotations we should take them only from the current class and run them, no checks for parent contracts. In this way we can give an ability to weaken them. But we SHOULD check special cases for all possible `inheritDoc` comments in our doc block.

**Comment by pdaw** [comment]
@lisachenko 

 Thanks for your full and detailed answer :) I'll try to implement it in free time.

**Comment by lisachenko** [comment]
Closed in #10, released in 0.4.0
